config/routes.rb
Rails.application.routes.draw do

root 'welcome#index'

get 'student/single' => 'student#single' , as: :single
get 'student/pairs'  => 'student#pairs' , as: :pairs

end

app/models/student.rb
class Student < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
  def single
    students = Student.all
    @student = students.sample
  end

  def pairs
    students = Student.all.map {|x| x}
puts "%"*50
puts students.length
    @pairs = []
    ((students.length / 2) + 1).times do | i |
      @pairs << students.sample(2)
      @pairs[i].each do |student|
        students.delete(student)
      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StudentSelector</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/student/pairs.html.erb
<% @pairs.each do |pair| %>
  <p>
    <%= "#{pair[0].fullname if pair[0]}" %>
    <%= "... #{pair[1].fullname}" if pair[1] %>
  </p>
<% end %>

<%= button_to "Single Student", single_path, method: "get" %>
<%= button_to "Pair Again", pairs_path, method: "get" %>

app/views/student/single.html.erb
<h1> <%= @student.fullname if @student %> </h1>


<%= button_to "Single Again", single_path, method: "get" %>
<%= button_to "Pair Students", pairs_path, method: "get" %>

app/views/welcome/index.html.erb
<%= link_to "single student", single_path %>
<%= link_to "pair student", pairs_path %>